#!/usr/bin/env bash
# diff-ledger.sh — track the bot's SUGGESTED diffs as an eval artifact.
#
# The eval measures triage quality; this measures the loop's OUTPUT: of the diffs the
# bot suggests, how many LAND vs get ABANDONED (proposal precision). High abandon rate =
# the loop proposes low-value churn = an evolve target.
#
# Queries Phabricator for autonomous OT-bot diffs (title [OT*]/[Oncall]/sync) in a window,
# classifies by category, computes land/abandon/revert rates, writes a ledger .md + .json.
#
# Usage: diff-ledger.sh [days_back]   (default 60)
set -uo pipefail
DAYS="${1:-60}"
OUTDIR="$HOME/notes/users/dennyzhang/projects/mrs-ot-agent-context/eval/reports"
AFTER=$(python3 -c "import datetime; print((datetime.date.today()-datetime.timedelta(days=$DAYS)).isoformat())")
TODAY=$(python3 -c "import datetime; print(datetime.date.today().isoformat())")
JSON=$(mktemp)
meta phabricator.diff list --author-is=dennyzhang --time-created-is-after="$AFTER" \
  --columns=number,title,status,created,ai_percentage -l 800 -o json 2>/dev/null > "$JSON" || { echo "meta query failed"; exit 1; }

python3 - "$JSON" "$OUTDIR" "$AFTER" "$TODAY" <<'PY'
import json,re,sys
rows=json.load(open(sys.argv[1])); rows=rows if isinstance(rows,list) else rows.get('data',[])
outdir,after,today=sys.argv[2],sys.argv[3],sys.argv[4]
def autobot(t):
    t=t or ''
    return bool(re.match(r'\[(OT|Oncall|OT bot|OT Master Agent|OT - |Myclaw|Observability\]\[OT)',t)) or 'knowledge-distillation' in t.lower()
bot=[r for r in rows if autobot(r.get('title'))]
def cat(t):
    t=(t or '').lower()
    if 'mirror' in t or '[ot bot sync]' in t: return 'notes-sync'
    if re.search(r'detector|alert|configo|suppress|widen|threshold|publish error|no data|heartbeat|gmpp|relogger|subscription',t): return 'detector/alert-fix'
    if re.search(r'known_patterns|\bp[0-9]{2}\b|quality rule|\br[0-9]{1,2}\b|catalog|distill|pattern|failure-mode|lessons',t): return 'knowledge'
    if re.search(r'cron|setup-cron|bootstrap|backup|claude.md|identity|scope|lane|migrate|plugin|hook|symlink',t): return 'cron/infra'
    if re.search(r'report|shift|brief|summary|gdoc|crisp|threading',t): return 'reporting'
    return 'other'
LANDED={'Closed','Committed'}
from collections import Counter,defaultdict
n=len(bot); landed=sum(1 for r in bot if str(r.get('status')) in LANDED)
ab=sum(1 for r in bot if str(r.get('status'))=='Abandoned'); rv=sum(1 for r in bot if str(r.get('status'))=='Reverted')
opn=n-landed-ab-rv
def rate(x): return f'{100*x/n:.0f}%' if n else 'n/a'
# per-category land rate
cg=defaultdict(lambda:[0,0])
for r in bot:
    c=cat(r.get('title')); cg[c][0]+=1
    if str(r.get('status')) in LANDED: cg[c][1]+=1
L=[f'# Suggested-diff ledger — bot proposal precision ({after} → {today})','',
   '_Generated by `tools/diff-ledger.sh`. The eval tracks the loop OUTPUT: land vs abandon = proposal precision._','',
   '## Metrics',
   f'- **suggested: {n}** · landed {landed} (**{rate(landed)} land rate**) · abandoned {ab} ({rate(ab)}) · reverted {rv} · open {opn}',
   '',
   '| category | suggested | landed | land rate |','|---|---|---|---|']
for c,(tot,ld) in sorted(cg.items(),key=lambda kv:-kv[1][0]):
    L.append(f'| {c} | {tot} | {ld} | {100*ld//tot if tot else 0}% |')
L+=['','## Full list','','| # | status | created | category | title |','|---|---|---|---|---|']
for r in sorted(bot,key=lambda r:str(r.get('created'))):
    L.append('| %s | %s | %s | %s | %s |'%(r.get('number'),str(r.get('status'))[:9],str(r.get('created'))[:10],cat(r.get('title')),str(r.get('title')).replace('|','/')[:88]))
md=f'{outdir}/diff-ledger.md'
open(md,'w').write('\n'.join(L)+'\n')
json.dump({'window':[after,today],'suggested':n,'landed':landed,'land_rate':round(landed/n,3) if n else None,'abandoned':ab,'reverted':rv,'open':opn,'by_category':{c:{'suggested':t,'landed':l} for c,(t,l) in cg.items()}},
          open(f'{outdir}/diff-ledger.json','w'),indent=1)
# time-series: append one metrics row per run (idempotent per day) so proposal precision TRENDS
import os,datetime
hist=f'{outdir}/diff-ledger-history.jsonl'
wd=(datetime.date.fromisoformat(today)-datetime.date.fromisoformat(after)).days
row={'date':today,'window_days':wd,'suggested':n,'landed':landed,'land_rate':round(landed/n,3) if n else None,'abandon_rate':round(ab/n,3) if n else None,'reverted':rv,'open':opn}
lines=[l for l in (open(hist).read().splitlines() if os.path.exists(hist) else []) if l.strip() and json.loads(l).get('date')!=today]
lines.append(json.dumps(row))
open(hist,'w').write('\n'.join(lines)+'\n')
print(f'suggested {n} | landed {landed} ({rate(landed)}) | abandoned {ab} ({rate(ab)}) | reverted {rv} | open {opn}')
print('wrote',md,'+ diff-ledger.json + diff-ledger-history.jsonl')
PY
rm -f "$JSON"
