#!/usr/bin/env bash
# escalation-rate.sh — the HUMAN-ESCALATION metric for the eval scoreboard.
#
# The whole point of the agent is to handle OT incidents WITHOUT a human. When it can't
# resolve one, it POPS it to a human (posts to the TEAM myclaw space). This measures how
# often that happens:
#
#   human-escalation rate = routed_to='human' / all triaged incidents
#
# GOAL: trends DOWN to ~5% as the agent improves (autonomy = 1 - escalation). A rising rate
# = the agent is regressing or hitting a new failure class it can't own.
#
# Reads the triage_events substrate (written by record-triage-event.sh --routed-to). Writes a
# report .md + .json and appends one row per run to a time-series .jsonl so the rate TRENDS.
#
# Usage: escalation-rate.sh [days_back]   (default 30)
set -uo pipefail
DAYS="${1:-30}"
DB="$HOME/.myclaw-ot-bot/spaces/AAQAVOjYc80/myclaw.db"
OUTDIR="$HOME/notes/users/dennyzhang/projects/mrs-ot-agent-context/eval/reports"
TARGET="0.05"   # the goal: ~5% of incidents need a human

# additive column may not exist yet on an un-migrated db
sqlite3 "$DB" "SELECT 1 FROM pragma_table_info('triage_events') WHERE name='routed_to';" 2>/dev/null | grep -q 1 \
  || sqlite3 "$DB" "ALTER TABLE triage_events ADD COLUMN routed_to TEXT;" 2>/dev/null || true

AFTER=$(python3 -c "import datetime;print((datetime.date.today()-datetime.timedelta(days=$DAYS)).isoformat())")
TODAY=$(python3 -c "import datetime;print(datetime.date.today().isoformat())")

# rows in window; routed_to NULL is treated as 'auto' (autonomous is the default behavior)
read -r N HUMAN AUTO UNSET <<EOF
$(sqlite3 -separator ' ' "$DB" "
  SELECT
    COUNT(*),
    SUM(CASE WHEN routed_to='human' THEN 1 ELSE 0 END),
    SUM(CASE WHEN routed_to='auto' OR routed_to IS NULL THEN 1 ELSE 0 END),
    SUM(CASE WHEN routed_to IS NULL THEN 1 ELSE 0 END)
  FROM triage_events WHERE date(ts_notified) >= '$AFTER';" 2>/dev/null)
EOF
N=${N:-0}; HUMAN=${HUMAN:-0}; AUTO=${AUTO:-0}; UNSET=${UNSET:-0}

python3 - "$OUTDIR" "$AFTER" "$TODAY" "$N" "$HUMAN" "$AUTO" "$UNSET" "$TARGET" "$DAYS" <<'PY'
import json,sys,os,datetime
outdir,after,today,N,HUMAN,AUTO,UNSET,TARGET,DAYS=sys.argv[1:]
N,HUMAN,AUTO,UNSET,DAYS=int(N),int(HUMAN),int(AUTO),int(UNSET),int(DAYS)
TARGET=float(TARGET)
rate = round(HUMAN/N,3) if N else None
autonomy = round(1-HUMAN/N,3) if N else None
verdict = 'n/a' if rate is None else ('AT/BELOW target' if rate<=TARGET else 'ABOVE target — escalating too often')
L=[f'# Human-escalation rate — autonomy metric ({after} → {today}, {DAYS}d)','',
   '_Generated by `tools/escalation-rate.sh` from the `triage_events` substrate. The agent should handle incidents itself; escalation = it popped one to a human (TEAM space)._','',
   '## Metric',
   f'- **triaged: {N}** · escalated-to-human {HUMAN} · handled-autonomously {AUTO}',
   f'- **human-escalation rate: {"n/a" if rate is None else f"{rate:.1%}"}**  (target ≤ {TARGET:.0%}) → **{verdict}**',
   f'- autonomy rate: {"n/a" if autonomy is None else f"{autonomy:.1%}"}',
   '']
if UNSET:
    L.append(f'> ⚠️ {UNSET}/{N} rows have no explicit `routed_to` (counted as autonomous). Rate becomes exact once the monitors pass `--routed-to` on every event.')
    L.append('')
open(f'{outdir}/escalation-rate.md','w').write('\n'.join(L)+'\n')
json.dump({'window':[after,today],'window_days':DAYS,'triaged':N,'escalated_human':HUMAN,
           'auto':AUTO,'unset':UNSET,'human_escalation_rate':rate,'autonomy_rate':autonomy,
           'target':TARGET,'verdict':verdict},
          open(f'{outdir}/escalation-rate.json','w'),indent=1)
# time-series append (idempotent per day)
hist=f'{outdir}/escalation-rate-history.jsonl'
row={'date':today,'window_days':DAYS,'triaged':N,'escalated_human':HUMAN,
     'human_escalation_rate':rate,'autonomy_rate':autonomy}
lines=[l for l in (open(hist).read().splitlines() if os.path.exists(hist) else []) if l.strip() and json.loads(l).get('date')!=today]
lines.append(json.dumps(row))
open(hist,'w').write('\n'.join(lines)+'\n')
print(f'triaged {N} | escalated-to-human {HUMAN} | rate {"n/a" if rate is None else f"{rate:.1%}"} (target ≤{TARGET:.0%}) -> {verdict}')
print('wrote escalation-rate.md + .json + escalation-rate-history.jsonl')
PY
