#!/usr/bin/env bash
# ot-ingest-diffs — mirrors authored-diffs metadata for OT key people
# Reads: mrs-ot-agent-context/references/key-people.json + references/diffs/diff-sources.json
# Writes: mrs-ot-agent-context/references/diffs/<unixname>.md + README.md
# Outputs: final line = JSON summary {"summary":{...}}
# read-only on Phabricator (no write-back)

set -euo pipefail

CONTEXT_DIR=~/notes/users/dennyzhang/projects/mrs-ot-agent-context
ROSTER_FILE=$CONTEXT_DIR/references/key-people.json
SOURCES_FILE=$CONTEXT_DIR/references/diffs/diff-sources.json
OUT_DIR=$CONTEXT_DIR/references/diffs
CHANGED_SIDECAR=~/.myclaw-ot-bot/ot-ingest-diffs-changed.json

NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
ERRORS=0
ERROR_KIND=""
WRITTEN=0
CHANGED_COUNT=0
TOTAL_DIFFS=0
AUTHORS_WITH_DIFFS=0

# Read run knobs
LOOKBACK_DAYS=$(python3 -c "import json; d=json.load(open('$SOURCES_FILE')); print(d.get('lookback_days',14))" 2>/dev/null || echo 14)
PER_AUTHOR_LIMIT=$(python3 -c "import json; d=json.load(open('$SOURCES_FILE')); print(d.get('per_author_limit',20))" 2>/dev/null || echo 20)
CANDIDATE_ROTATION=$(python3 -c "import json; d=json.load(open('$SOURCES_FILE')); print(d.get('candidate_rotation','mrs_online_training'))" 2>/dev/null || echo "mrs_online_training")
LOOKBACK_DATE=$(date -u -d "$LOOKBACK_DAYS days ago" +"%Y-%m-%d" 2>/dev/null || date -u -v-${LOOKBACK_DAYS}d +"%Y-%m-%d")

# Get curated roster (people whose surfaces include 'diffs')
ROSTER_JSON=$(python3 -c "
import json
data = json.load(open('$ROSTER_FILE'))
people = [p for p in data.get('people',[]) if 'diffs' in p.get('surfaces',[])]
print(json.dumps(people))
" 2>/dev/null)

if [ -z "$ROSTER_JSON" ] || [ "$ROSTER_JSON" = "[]" ]; then
    ERRORS=1
    ERROR_KIND="empty_roster"
    echo '{"summary":{"authors":0,"authors_with_diffs":0,"diffs":0,"written":0,"changed":0,"errors":1,"lookback_days":'$LOOKBACK_DAYS'}}'
    exit 0
fi

# Get candidate rotation members (propose-only, never auto-ingest)
ROTATION_MEMBERS=$(meta oncall.rotation.members list --rotation=$CANDIDATE_ROTATION -o json 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); items=d if isinstance(d,list) else d.get('data',[]); print(json.dumps([r.get('unixname','') for r in items]))" 2>/dev/null || echo "[]")
ROSTER_UNIXNAMES=$(echo "$ROSTER_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(json.dumps([p['unixname'] for p in d]))")

CHANGED_ENTRIES="[]"

# Per-author fetch and write
while IFS= read -r person_json; do
    UNIXNAME=$(echo "$person_json" | python3 -c "import json,sys; print(json.loads(sys.stdin.read())['unixname'])")
    TRUST=$(echo "$person_json" | python3 -c "import json,sys; print(json.loads(sys.stdin.read()).get('trust',2))")
    DOMAINS=$(echo "$person_json" | python3 -c "import json,sys; print(', '.join(json.loads(sys.stdin.read()).get('domains',[])))")

    TMPFILE=/tmp/ot-phab-diffs-$UNIXNAME.json
    meta phabricator.diff list --author-is=$UNIXNAME --time-created-is-after=$LOOKBACK_DATE --limit=$PER_AUTHOR_LIMIT -o json > "$TMPFILE" 2>/dev/null
    
    COUNT=$(python3 -c "import json; d=json.load(open('$TMPFILE')); items=d if isinstance(d,list) else d.get('data',[]); print(len(items))" 2>/dev/null || echo 0)
    
    if [ "$COUNT" -gt 0 ]; then
        AUTHORS_WITH_DIFFS=$((AUTHORS_WITH_DIFFS+1))
        TOTAL_DIFFS=$((TOTAL_DIFFS+COUNT))

        OUTFILE=$OUT_DIR/$UNIXNAME.md
        PREV_HASH=""
        [ -f "$OUTFILE" ] && PREV_HASH=$(md5sum "$OUTFILE" | cut -d' ' -f1)

        python3 -c "
import json
author='$UNIXNAME'
trust=$TRUST
domains='$DOMAINS'
data=json.load(open('$TMPFILE'))
items=data if isinstance(data,list) else data.get('data',[])
print('---')
print(f'author: {author}')
print(f'trust: {trust}')
print(f'domains: [{domains}]')
print(f'last_synced: $NOW')
print(f'lookback_days: $LOOKBACK_DAYS')
print('---')
print('<!-- AUTO-GENERATED by ot-ingest-diffs. DO NOT EDIT. -->')
print()
print(f'# Authored diffs — {author} (trust {trust})')
print()
for item in items:
    n=item['number'].lstrip('D')
    title=item['title'][:120]
    status=item['status']
    created=item.get('created','')[:10]
    summary=(item.get('summary','') or '')[:300].replace(chr(10),' ')
    url=item.get('url','')
    print(f'## D{n} — {title}')
    print(f'- **status**: {status}')
    print(f'- **created**: {created}')
    print(f'- **url**: {url}')
    if summary:
        print(f'- **summary**: {summary}')
    print()
" > "$OUTFILE"

        NEW_HASH=$(md5sum "$OUTFILE" | cut -d' ' -f1)
        if [ "$PREV_HASH" != "$NEW_HASH" ]; then
            CHANGED_COUNT=$((CHANGED_COUNT+1))
        fi
        WRITTEN=$((WRITTEN+1))
    fi
done < <(echo "$ROSTER_JSON" | python3 -c "import json,sys; [print(json.dumps(p)) for p in json.load(sys.stdin)]")

# Build changed.json sidecar (capped at 40, highest-trust-first)
python3 -c "
import json, os
roster = json.loads('''$ROSTER_JSON''')
trust_map = {p['unixname']: p.get('trust',2) for p in roster}
domain_map = {p['unixname']: p.get('domains',[]) for p in roster}
changed = []
for p in roster:
    u = p['unixname']
    f = f'/tmp/ot-phab-diffs-{u}.json'
    if not os.path.exists(f): continue
    data = json.load(open(f))
    items = data if isinstance(data,list) else data.get('data',[])
    for item in items:
        changed.append({'number': item['number'], 'title': item['title'], 'summary': (item.get('summary','') or '')[:400], 'status': item['status'], 'author': u, 'trust': trust_map.get(u,2), 'domains': domain_map.get(u,[]), 'created': item.get('created','')[:10], 'change': 'new'})
changed.sort(key=lambda x: (x['trust'], x['created']), reverse=True)
capped = len(changed) > 40
changed = changed[:40]
json.dump({'changed': changed, 'count': len(changed), 'capped': capped}, open('$CHANGED_SIDECAR','w'), indent=2)
" 2>/dev/null

# Candidate discovery (propose-only)
CANDIDATES=$(python3 -c "
import json
rotation = json.loads('''$ROTATION_MEMBERS''')
roster = json.loads('''$ROSTER_UNIXNAMES''')
candidates = [u for u in rotation if u and u not in roster]
print(', '.join(candidates) if candidates else 'none')
" 2>/dev/null || echo "unknown")

# Write README
TOTAL_AUTHORS=$(echo "$ROSTER_JSON" | python3 -c "import json,sys; print(len(json.load(sys.stdin)))")
python3 -c "
import json
roster = json.loads('''$ROSTER_JSON''')
print('<!-- AUTO-GENERATED by ot-ingest-diffs. DO NOT EDIT. -->')
print('# OT Key-People Authored Diffs')
print()
print('Change-metadata corpus for the change-delta-first triage step.')
print()
print('| Author | Trust | Domains | File |')
print('|--------|-------|---------|------|')
for p in roster:
    u=p['unixname']; t=p.get('trust',2); d=', '.join(p.get('domains',[])); n=p.get('name',u)
    print(f'| {n} ({u}) | {t} | {d} | [{u}.md]({u}.md) |')
print()
print(f'**Candidate discovery ($CANDIDATE_ROTATION rotation):** $CANDIDATES')
" > $OUT_DIR/README.md

# Output summary JSON (last line stdout)
echo '{"summary":{"authors":'$TOTAL_AUTHORS',"authors_with_diffs":'$AUTHORS_WITH_DIFFS',"diffs":'$TOTAL_DIFFS',"written":'$WRITTEN',"changed":'$CHANGED_COUNT',"errors":'$ERRORS',"lookback_days":'$LOOKBACK_DAYS'}}'
