#!/usr/bin/env bash
# cron-project-dashboard.sh — Generate per-project DASHBOARD.md health metrics.
#
# For every project in projects/_registry.json, computes signal-side metrics and
# writes projects/<slug>/context/DASHBOARD.md. Designed to be cheap (no network),
# so it can run after every harvester refresh.
#
# Metrics computed (all from local files):
#   - Signal entries per harvester (count of `| ... |` table rows)
#   - Undigested entries: rows with date > SNAPSHOT's `Distilled through:` date
#   - Days since SNAPSHOT.md was touched (file mtime)
#   - Top diff authors not in `key_people:` (promote candidates)
#   - key_people with no recent signal (demote candidates)
#
# Schedule: runs immediately after cron-project-context-refresh.sh (Mon 04:30).

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$HOME/work/claude"
PROJECTS_DIR="$REPO_DIR/projects"
REGISTRY="$PROJECTS_DIR/_registry.json"
LOG_PREFIX="$(date '+%Y-%m-%d %H:%M')"
TODAY=$(date '+%Y-%m-%d')

# shellcheck disable=SC1091
source "$SCRIPT_DIR/cron-alert.sh"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/harvesters/_lib.sh"

echo "$LOG_PREFIX === Project dashboard generation ==="

if [ ! -f "$REGISTRY" ]; then
    cron_alert "project-dashboard" "Registry missing: $REGISTRY"
    exit 1
fi

slugs=$(python3 -c "import json; [print(p) for p in json.load(open('$REGISTRY')).get('projects',[])]")

projects_done=0

for slug in $slugs; do
    project_dir="$PROJECTS_DIR/$slug"
    [ -d "$project_dir" ] || continue
    meta_file="$project_dir/META.yaml"
    [ -f "$meta_file" ] || continue

    context_dir="$project_dir/context"
    [ -d "$context_dir" ] || { echo "$LOG_PREFIX   [skip] $slug has no context/ dir"; continue; }

    signal_dir="$context_dir/signals"
    snapshot="$context_dir/SNAPSHOT.md"
    dashboard="$context_dir/DASHBOARD.md"
    tmpout=$(mktemp -t dashboard.XXXX.md)

    # Distillation cutoff: read `Distilled through: YYYY-MM-DD` from SNAPSHOT.
    distilled_through=""
    if [ -f "$snapshot" ]; then
        distilled_through=$(grep -m1 -oE 'Distilled through:[[:space:]]*[0-9]{4}-[0-9]{2}-[0-9]{2}' "$snapshot" 2>/dev/null \
            | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}' || true)
    fi

    snapshot_mtime_days=""
    if [ -f "$snapshot" ]; then
        mtime_epoch=$(stat -c %Y "$snapshot" 2>/dev/null || echo 0)
        now_epoch=$(date +%s)
        snapshot_mtime_days=$(( (now_epoch - mtime_epoch) / 86400 ))
    fi

    {
        echo "# Project Health Dashboard — $slug"
        echo
        echo "<!-- Auto-generated by cron-project-dashboard.sh. Do not hand-edit. -->"
        echo "<!-- Last refresh: $(date -Iseconds) -->"
        echo
        echo "## Snapshot freshness"
        echo
        echo "| Metric | Value | Threshold | Status |"
        echo "|--------|-------|-----------|--------|"
        if [ -n "$snapshot_mtime_days" ]; then
            status="green"
            [ "$snapshot_mtime_days" -gt 14 ] && status="yellow"
            [ "$snapshot_mtime_days" -gt 30 ] && status="red"
            echo "| Days since SNAPSHOT touched | $snapshot_mtime_days | <14 | $status |"
        else
            echo "| Days since SNAPSHOT touched | _no SNAPSHOT.md_ | — | red |"
        fi
        echo "| Distilled through | ${distilled_through:-_unset — add 'Distilled through: YYYY-MM-DD' to SNAPSHOT_} | — | — |"
        echo
        echo "## Signal volume per harvester"
        echo
        echo "| Harvester | Total entries | Undigested |"
        echo "|-----------|--------------|-----------|"
    } > "$tmpout"

    total_signals=0
    undigested_total=0

    if [ -d "$signal_dir" ]; then
        for sigfile in "$signal_dir"/*.md; do
            [ -f "$sigfile" ] || continue
            # Only count files emitted by harvesters — they all carry a "<!-- Source: -->" marker.
            grep -q '<!-- Source:' "$sigfile" 2>/dev/null || continue
            name=$(basename "$sigfile" .md)

            # Count data rows: lines starting with `| ` that aren't header/separator.
            # Header: `| Date | Diff | ...`  Separator: `|------|...|`
            total=$(grep -cE '^\| [0-9]{4}-[0-9]{2}-[0-9]{2}' "$sigfile" 2>/dev/null) || total=0
            undigested="$total"
            if [ -n "$distilled_through" ]; then
                undigested=$(awk -v cutoff="$distilled_through" '
                    /^\| [0-9]{4}-[0-9]{2}-[0-9]{2}/ {
                        match($0, /[0-9]{4}-[0-9]{2}-[0-9]{2}/);
                        date = substr($0, RSTART, RLENGTH);
                        if (date > cutoff) c++;
                    }
                    END { print c+0 }
                ' "$sigfile")
            fi
            total_signals=$((total_signals + total))
            undigested_total=$((undigested_total + undigested))
            echo "| $name | $total | $undigested |" >> "$tmpout"
        done
    fi

    {
        echo
        echo "**Total undigested:** $undigested_total"
        if [ "$undigested_total" -gt 30 ]; then
            echo
            echo "⚠️  **Action**: >30 undigested entries. Distill into SNAPSHOT and bump 'Distilled through:' to today."
        fi
        echo
        echo "## People activity"
        echo
    } >> "$tmpout"

    # Compute key_people activity: who appears as Author in diffs-by-path within last 90d.
    key_people=$(read_yaml_list key_people "$meta_file" 2>/dev/null)
    by_path="$signal_dir/diffs-by-path.md"

    if [ -n "$key_people" ] && [ -f "$by_path" ]; then
        # Extract authors from diffs-by-path table rows, count occurrences.
        observed=$(awk -F'|' '
            /^\| [0-9]{4}-[0-9]{2}-[0-9]{2}/ {
                gsub(/^[ \t]+|[ \t]+$/, "", $5);
                if ($5 != "") print $5
            }
        ' "$by_path" | sort | uniq -c | sort -rn)

        echo "**Top observed authors in workstream paths (last harvest):**" >> "$tmpout"
        echo >> "$tmpout"
        echo '```' >> "$tmpout"
        echo "$observed" | head -10 >> "$tmpout"
        echo '```' >> "$tmpout"
        echo >> "$tmpout"

        echo "**Promote candidates** (≥3 diffs, NOT in \`key_people:\`):" >> "$tmpout"
        echo >> "$tmpout"
        promote=$(echo "$observed" | awk -v people="$(echo "$key_people" | tr '\n' ' ')" '
            {
                count = $1
                author = $2
                if (count >= 3) {
                    n = split(people, arr, " ")
                    found = 0
                    for (i=1; i<=n; i++) if (arr[i] == author) { found=1; break }
                    if (!found) print "  - " author " (" count " diffs)"
                }
            }
        ')
        if [ -n "$promote" ]; then
            echo "$promote" >> "$tmpout"
        else
            echo "  _(none)_" >> "$tmpout"
        fi
        echo >> "$tmpout"

        echo "**Demote candidates** (in \`key_people:\` with 0 observed diffs in workstream):" >> "$tmpout"
        echo >> "$tmpout"
        observed_names=$(echo "$observed" | awk '{print $2}')
        demote=""
        while read -r p; do
            [ -z "$p" ] && continue
            if ! echo "$observed_names" | grep -qx "$p"; then
                demote+="  - $p"$'\n'
            fi
        done <<< "$key_people"
        if [ -n "$demote" ]; then
            echo "$demote" >> "$tmpout"
        else
            echo "  _(none)_" >> "$tmpout"
        fi
    else
        echo "_No key_people declared OR no diffs-by-path harvest yet._" >> "$tmpout"
    fi

    mv "$tmpout" "$dashboard"
    projects_done=$((projects_done + 1))
    echo "$LOG_PREFIX   wrote $dashboard"
done

write_heartbeat "project-dashboard" 2>/dev/null || true
echo "$LOG_PREFIX Summary: $projects_done dashboard(s) written"
cron_alert_clear "project-dashboard" 2>/dev/null || true
echo "$LOG_PREFIX === Done ==="
