#!/bin/bash
# cron-harness-health.sh — generate state/HARNESS-HEALTH.md daily.
# Aggregates: hook latency p50/p95, cron success rate (7d), settings.json drift,
#             nudge effectiveness, sync-hook count vs CLAUDE.md threshold.
#
# Cron: 0 7 * * *  (daily 7am after morning-gchat).

set -uo pipefail

CLAUDE_DIR="$HOME/work/claude"
OUT="$CLAUDE_DIR/state/HARNESS-HEALTH.md"
LOG_DIR="$HOME/logs"
HOOK_TIMINGS="$LOG_DIR/hook-timings.csv"
METRICS="$CLAUDE_DIR/state/CRON-HEALTH-METRICS.md"
SETTINGS="$CLAUDE_DIR/.claude/settings.json"
TS=$(date '+%Y-%m-%d %H:%M %Z')

# shellcheck source=/dev/null
source "$CLAUDE_DIR/scripts/cron-alert.sh" 2>/dev/null || true

# Compute via python for clean stats.
/usr/bin/python3 - "$HOOK_TIMINGS" "$METRICS" "$SETTINGS" "$OUT" "$TS" <<'PY'
import json, os, sys, csv, time, statistics
from collections import defaultdict, Counter

timings_path, metrics_path, settings_path, out_path, ts = sys.argv[1:6]

# 1. Hook latency
hook_stats = []
if os.path.exists(timings_path):
    rows = defaultdict(list)
    fail_counts = defaultdict(int)
    with open(timings_path) as f:
        for line in f:
            parts = line.strip().split(",")
            # Format: epoch_ms,name,duration_ms[,exit_code]
            if len(parts) < 3: continue
            try:
                rows[parts[1]].append(int(parts[2]))
                if len(parts) >= 4 and parts[3] != "0":
                    fail_counts[parts[1]] += 1
            except: pass
    for name, durations in sorted(rows.items()):
        if not durations: continue
        durations.sort()
        p50 = durations[len(durations)//2]
        p95 = durations[int(len(durations)*0.95)] if len(durations) > 1 else durations[0]
        hook_stats.append((name, len(durations), p50, p95, fail_counts[name]))

# 2. Cron success rate (7d rolling)
cron_stats = defaultdict(lambda: {"success": 0, "failure": 0})
if os.path.exists(metrics_path):
    cutoff = time.time() - 7*86400
    with open(metrics_path) as f:
        for line in f:
            if not line.startswith("| "): continue
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) < 6: continue
            date, _t, job, result, _d, _f = cells[:6]
            try:
                row_time = time.mktime(time.strptime(date, "%Y-%m-%d"))
            except: continue
            if row_time < cutoff: continue
            if result in ("success", "failure"):
                cron_stats[job][result] += 1

# 3. Settings.json structural state
sync_pretooluse_bash = 0
total_hooks = 0
matchers = 0
if os.path.exists(settings_path):
    s = json.load(open(settings_path))
    for ev, mlist in s.get("hooks", {}).items():
        for m in mlist:
            matchers += 1
            for h in m.get("hooks", []):
                total_hooks += 1
                if ev == "PreToolUse" and m.get("matcher") == "Bash" and not h.get("async", False):
                    sync_pretooluse_bash += 1

# 4. Render markdown
lines = [
    "# Harness Health",
    "",
    f"*Auto-generated by `cron-harness-health.sh` — last run: {ts}*",
    "",
    "## Hook config (settings.json)",
    "",
    f"- **Total hooks**: {total_hooks} across {matchers} matchers",
    f"- **Sync PreToolUse Bash hooks**: {sync_pretooluse_bash} {'[FLAG] exceeds CLAUDE.md threshold of 4' if sync_pretooluse_bash > 4 else '[OK] within threshold'}",
    "",
    "## Hook latency (last logged window)",
    "",
]
if hook_stats:
    lines.append("| Hook | N | p50 (ms) | p95 (ms) | Non-zero exits |")
    lines.append("|---|---|---|---|---|")
    for name, n, p50, p95, fails in hook_stats:
        flag = " [FLAG]" if fails > 0 else ""
        lines.append(f"| {name} | {n} | {p50} | {p95} | {fails}{flag} |")
else:
    lines.append("_No timing data yet — invoke any hook to populate `~/logs/hook-timings.csv` via the `_run-with-timing.sh` wrapper._")
lines.append("")

lines.extend([
    "## Cron success rate (7-day rolling)",
    "",
    "| Job | Success | Failure | Rate |",
    "|---|---|---|---|",
])
for job in sorted(cron_stats.keys()):
    s = cron_stats[job]["success"]; f = cron_stats[job]["failure"]
    total = s + f
    rate = f"{100*s/total:.0f}%" if total else "—"
    flag = " [FLAG]" if total > 0 and s/total < 0.7 else ""
    lines.append(f"| {job} | {s} | {f} | {rate}{flag} |")

lines.extend([
    "",
    "## How to read",
    "",
    "- **[FLAG] on cron rate**: success rate <70% over 7 days — candidate for `cron-remediator.sh` pattern entry, or retire if low-leverage.",
    "- **[FLAG] on sync hooks**: per CLAUDE.md hook performance rule, >4 sync PreToolUse Bash hooks fire on every Bash invocation. Convert log-only ones to `async: true` in `config/hooks.yaml`.",
    "- **No hook latency data**: timing is captured by `config/hooks/_run-with-timing.sh` (wrapper auto-applied by render-hooks.sh for all script-type hooks). If column is empty, hooks may not have fired yet, or `~/logs/hook-timings.csv` was rotated.",
    "",
])

with open(out_path, "w") as f:
    f.write("\n".join(lines))

print(f"OK: wrote {out_path} ({len(lines)} lines)")
PY

# Heartbeat for staleness detection (per CLAUDE.md cron infrastructure rule)
type write_heartbeat &>/dev/null && write_heartbeat "harness-health" || true
